name: Makefile test

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: set up repository
      run : sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install build-essential -y
    
    - name: fork test
      run: cc ./fork/fork.c -o fork && ./fork/fork
